language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."

install:
  - composer update -n --prefer-dist
  # pthreads is now only supported on PHP 7.2+
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar;
      chmod +x coveralls.phar;
      travis/install-pthreads.sh;
    fi

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  # Coverage only on 7.2+ due to pthreads compatibility
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then
      ./coveralls.phar -v;
    fi

cache:
  directories:
    - $HOME/.composer/cache/files
