language: php
dist: xenial
os: linux

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."

install:
  - composer update -n --prefer-dist
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - chmod +x coveralls.phar
  - travis/install-pcov.sh

script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then
      vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml;
    else
      vendor/bin/phpunit;
    fi
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - if [ -f build/logs/clover.xml ]; then
      ./coveralls.phar -v;
    fi

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer
