name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      matrix:
        include:
          - operating-system: 'ubuntu-latest'
            php-version: '7.1'
            composer-require-checker-version: none

          - operating-system: 'ubuntu-latest'
            php-version: '7.2'
            composer-require-checker-version: 2.1.0

          - operating-system: 'ubuntu-latest'
            php-version: '7.3'
            composer-require-checker-version: 2.1.0

          - operating-system: 'ubuntu-latest'
            php-version: '7.4'
            composer-require-checker-version: 3.3.0

          - operating-system: 'ubuntu-latest'
            php-version: '8.0'
            composer-flags: '--ignore-platform-req=php'
            composer-require-checker-version: 3.3.0

          - operating-system: 'windows-latest'
            php-version: '7.4'
            composer-require-checker-version: 3.3.0
            job-description: 'on Windows'

          - operating-system: 'macos-latest'
            php-version: '7.4'
            composer-require-checker-version: 3.3.0
            job-description: 'on macOS'

    name: PHP ${{ matrix.php-version }} ${{ matrix.job-description }}

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}-${{ matrix.composer-flags }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}-
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          retry_wait_seconds: 30
          command: |
            composer update --optimize-autoloader --no-interaction --no-progress ${{ matrix.composer-flags }}
            composer info -D

      - name: Run tests
        run: vendor/bin/phpunit ${{ matrix.phpunit-flags }}

      - name: Run style fixer
        run: vendor/bin/php-cs-fixer --diff --dry-run -v fix
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1

      - name: Install composer-require-checker
        run: php -r 'file_put_contents("composer-require-checker.phar", file_get_contents("https://github.com/maglnet/ComposerRequireChecker/releases/download/${{ matrix.composer-require-checker-version }}/composer-require-checker.phar"));'
        if: runner.os != 'Windows' && matrix.composer-require-checker-version != 'none'

      - name: Run composer-require-checker
        run: php composer-require-checker.phar check composer.json --config-file $PWD/composer-require-check.json
        if: runner.os != 'Windows' && matrix.composer-require-checker-version != 'none'
